apiVersion: v1
kind: Service
metadata:
  name: kafka-0
  labels:
    app: kafka-0
spec:
  type: NodePort
  ports:
  - port: 9092
    targetPort: 9092
    nodePort: 32000
    name: kafka-0
  selector:
    app: kafka-0
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1
  labels:
    app: kafka-1
spec:
  clusterIP: None
  ports:
  - port: 9092
    name: kafka-1
  selector:
    app: kafka-1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2
  labels:
    app: kafka-2
spec:
  clusterIP: None
  ports:
  - port: 9092
    name: kafka-2
  selector:
    app: kafka-2

