apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cruis
spec:
  minReadySeconds: 1
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: kafka-cruis
  template:
    metadata:
      annotations:
      labels:
        app: kafka-cruis
    spec:
      containers:
      - name: kafka-cruis
        image: arjun/cruise-control:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: ui
          containerPort: 8090
          protocol: TCP
        - name: api
          containerPort: 42675
          protocol: TCP
        env:
        - name: PODINFO_UI_COLOR
          value: "#34577c"
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
