apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - kafka-deployment.yaml
  - kafka-service.yaml
  #- scale-kafka.yaml
  - scale-service-kafka.yaml
  - pvc.yaml
  - kafka-job.yaml
  - job-cm.yaml
