apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-0-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/arjun_vk/k8s/kafka/kafka-ui/flux/log/kafka-0
