apiVersion: v1
kind: Service
metadata:
  name: kafka-3
  labels:
    app: kafka-3
spec:
  clusterIP: None
  ports:
  - port: 9092
    name: kafka-3
  selector:
    app: kafka-3
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-4
  labels:
    app: kafka-4
spec:
  clusterIP: None
  ports:
  - port: 9092
    name: kafka-4
  selector:
    app: kafka-4
