apiVersion: v1
kind: Service
metadata:
  name: kafka-cruis-control
spec:
  type: ClusterIP
  selector:
    app: kafka-cruis-control
  ports:
    - name: ui
      port: 8090
      protocol: TCP
      targetPort: 8090
    - port: 42675
      targetPort: 42675
      protocol: TCP
      name: cruise-control-api
