apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  logging-data
  namespace: kube-logging
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
