apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cruis-control
spec:
  replicas: 2
  minReadySeconds: 1
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: kafka-cruis-control
  template:
    metadata:
      annotations:
      labels:
        app: kafka-cruis-control
    spec:
      containers:
      - name: kafka-cruis-control
        image: arjunvkrishna/cruise-control:1.0.5
        imagePullPolicy: Always
        ports:
        - name: ui
          containerPort: 8090
          protocol: TCP
        - name: api
          containerPort: 42675
          protocol: TCP
        env:
        - name: PODINFO_UI_COLOR
          value: "#34577c"
        - name: KAFKA_URL
          value: kafka-0
        - name: KAFKA_PORT
          value: 9092
       # - name: KAFKA_URL
       #   value: kafka-0:9092,kafka-1:9092,kafka-2:9092

          initialDelaySeconds: 5
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 50Mi
