apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cruis-control
spec:
  replicas: 2
  minReadySeconds: 1
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: kafka-cruis-control
  template:
    metadata:
      annotations:
      labels:
        app: kafka-cruis-control
    spec:
      containers:
      - name: kafka-cruis-control
        image: arjunvkrishna/cruise-control:1.0.4
        imagePullPolicy: Always
        ports:
        - name: ui
          containerPort: 8090
          protocol: TCP
        - name: api
          containerPort: 42675
          protocol: TCP
        env:
        - name: PODINFO_UI_COLOR
          value: "#34577c"
        - name: KAFKA_URL
          value: "kafka-0:9092,kafka-1:9092,kafka-2:9092"
        - name: FAST_MODE
          value: "true"
        - name: MIN.VALID.PARTITION.RATIO
          value: ".8"
        - name: CPU.BALANCE.THRESHOLD
          value: "1.05"
        - name: DISK.BALANCE.THRESHOLD
          value: "1.05"
        - name: NETWORK.INBOUND.BALANCE.THRESHOLD
          value: "1.05"
        - name: NETWORK.OUTBOUND.BALANCE.THRESHOLD
          value: "1.05"
        - name: REPLICA.COUNT.BALANCE.THRESHOLD
          value: "1.05"
        - name: CPU.CAPACITY.THRESHOLD
          value: ".3"
        - name: DISK.CAPACITY.THRESHOLD
          value: ".5"
        - name: NETWORK.INBOUND.CAPACITY.THRESHOLD
          value: ".8"
        - name: NETWORK.OUTBOUND.CAPACITY.THRESHOLD
          value: ".8"
        - name: CPU.LOW.UTILIZATION.THRESHOLD
          value: ".1"
        - name: DISK.LOW.UTILIZATION.THRESHOLD
          value: ".1"
        - name: NETWORK.INBOUND.LOW.UTILIZATION.THRESHOLD
          value: ".1"
        - name: NETWORK.OUTBOUND.LOW.UTILIZATION.THRESHOLD
          value: ".1"
        - name: METRIC.ANOMALY.PERCENTILE.UPPER.THRESHOLD
          value: "80.0"
        - name: METRIC.ANOMALY.PERCENTILE.LOWER.THRESHOLD
          value: "20.0"


          initialDelaySeconds: 5
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 50Mi
