FROM adobe/cruise-control:latest
COPY ./cruisecontrol.properties /opt/cruise-control/config/cruisecontrol.properties
COPY start.sh /opt/cruise-control/start.sh
RUN chmod +x /opt/cruise-control/start.sh
