apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cruis-control-logging
  namespace: flux-system
spec:
  interval: 1m
  path: "./kustomize/efk"
  prune: true
  sourceRef:
    kind: GitRepository
    name: kafka-cruis
  targetNamespace: kube-logging
