apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka-ui
  namespace: flux-system
spec:
  interval: 1m
  path: "./kustomize/kafka-ui" 
  prune: true
  sourceRef:
    kind: GitRepository
    name: kafka-cruis
  targetNamespace: default  # Deploy to the default namespace
