apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kafka-ingress
  namespace: flux-system
spec:
  interval: 1m
  path: "./kustomize/ingress"
  prune: true
  sourceRef:
    kind: GitRepository
    name: kafka-cruis
  targetNamespace: default
