apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kafka-cruis
  namespace: flux-system
spec:
  interval: 1m
  path: "./kustomize"  # Adjust the path if necessary for your repo structure
  prune: true
  sourceRef:
    kind: GitRepository
    name: kafka-cruis
  targetNamespace: default  # Deploy to the default namespace
