apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
      - name: kafka-ui
        image: ghcr.io/kafbat/kafka-ui
        ports:
        - containerPort: 8080
        env:
        - name: DYNAMIC_CONFIG_ENABLED
          value: "true"
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: "kafka-0:9092,kafka-1:9092,kafka-2:9092"
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: "/kafbat-ui"
        - name: KAFKA_CLUSTERS_0_NAME
          value: "KAFKA_CLUSTERS_UI"
        - name: AUTH_TYPE
          value: "LOGIN_FORM"
        - name: SPRING_SECURITY_USER_NAME
          value: admin
        - name: SPRING_SECURITY_USER_PASSWORD
          value: admin
